# Auto-generated tool metadata - DO NOT EDIT
# Generated by scripts/extract_tool_metadata.py


TOOL_SCHEMAS = [
    {
        "name": "list_residues",
        "toolset": "structure",
        "description": "List all residues in a chain with their sequence numbers, names, and any insertion codes. Use this to check residue numbering before calling other residue-specific tools. Also reports gaps in numbering and modified residues.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_id": {
                    "type": "string",
                    "description": "4-character PDB identifier (e.g., '1ABC', '6VXX'). Use either this or pdb_path.",
                },
                "pdb_path": {"type": "string", "description": "Path to local PDB file. Use either this or pdb_id."},
                "chain_id": {"type": "string", "description": "Chain identifier (e.g., 'A', 'B')"},
            },
            "required": ["chain_id"],
        },
        "check_fn": None,
    },
    {
        "name": "load_structure",
        "toolset": "structure",
        "description": "Load a protein structure from the PDB by ID or from a local file. Returns structure details including resolution, method, chains, and ligands.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_id": {
                    "type": "string",
                    "description": "4-character PDB identifier (e.g., '1ABC', '6VXX'). Use either this or pdb_path.",
                },
                "pdb_path": {
                    "type": "string",
                    "description": "Path to local PDB/mmCIF file. Use either this or pdb_id.",
                },
            },
            "required": [],
        },
        "check_fn": None,
    },
    {
        "name": "get_residue_contacts",
        "toolset": "structure",
        "description": "Find all atoms within a cutoff distance of a target residue's atoms, classify the contact type, and return a detailed report.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_id": {
                    "type": "string",
                    "description": "4-character PDB identifier (e.g., '1ABC', '6VXX'). Use either this or pdb_path.",
                },
                "pdb_path": {"type": "string", "description": "Path to local PDB file. Use either this or pdb_id."},
                "chain_id": {"type": "string", "description": "Chain identifier (e.g., 'A', 'B')"},
                "residue_number": {"type": "integer", "description": "Residue sequence number in the chain"},
                "cutoff_angstroms": {
                    "type": "number",
                    "description": "Distance cutoff in Angstroms for contact detection (default: 4.5)",
                    "default": 4.5,
                },
            },
            "required": [],
        },
        "check_fn": None,
    },
    {
        "name": "compute_sasa",
        "toolset": "structure",
        "description": "Calculate solvent accessible surface area (SASA) for protein residues. Returns absolute SASA values, relative percent to Gly-X-Gly max, and classification (buried <20%, partial 20-50%, exposed >50%).",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_id": {"type": "string", "description": "PDB ID code (e.g., '1abc'). Use either this or pdb_path."},
                "pdb_path": {"type": "string", "description": "Path to local PDB file. Use either this or pdb_id."},
                "chain_id": {"type": "string", "description": "Chain identifier (e.g., 'A', 'B')"},
                "residue_range": {
                    "type": "string",
                    "description": "Residue range to analyze. Can be 'start-end' (e.g., '1-50') or comma-separated list (e.g., '1,3,5'). If not specified, analyzes all residues.",
                },
            },
            "required": ["chain_id"],
        },
        "check_fn": None,
    },
    {
        "name": "get_secondary_structure",
        "toolset": "structure",
        "description": "Assign secondary structure (helix, strand, coil) to a protein chain using DSSP. Returns grouped structural elements with residue ranges.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_id": {
                    "type": "string",
                    "description": "PDB identifier (e.g., '1abc'). Use either this or pdb_path.",
                },
                "pdb_path": {"type": "string", "description": "Path to local PDB file. Use either this or pdb_id."},
                "chain_id": {"type": "string", "description": "Chain identifier (e.g., 'A')"},
                "residue_range": {
                    "type": "string",
                    "description": "Optional residue range in 'start-end' format (e.g., '1-100')",
                    "default": None,
                },
            },
            "required": ["chain_id"],
        },
        "check_fn": None,
    },
    {
        "name": "compute_interface",
        "toolset": "structure",
        "description": "Identify interface residues between two chains. Computes buried surface area, key contacts, and interface composition. Essential for protein-protein interaction analysis.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_id": {
                    "type": "string",
                    "description": "4-character PDB identifier (e.g., '1ABC', '3HFM'). Use either this or pdb_path.",
                },
                "pdb_path": {"type": "string", "description": "Path to local PDB file. Use either this or pdb_id."},
                "chain_a": {"type": "string", "description": "First chain ID (e.g., 'A')"},
                "chain_b": {"type": "string", "description": "Second chain ID (e.g., 'B')"},
                "distance_cutoff": {
                    "type": "number",
                    "default": 5.0,
                    "description": "Distance cutoff for interface contacts in Angstroms (default 5.0)",
                },
            },
            "required": ["chain_a", "chain_b"],
        },
        "check_fn": None,
    },
    {
        "name": "align_structures",
        "toolset": "structure",
        "description": "Align two protein chains by Cα superposition and compute per-residue deviations. Returns RMSD, rotation matrix, shift vector, aligned length, and flags regions with >2A deviation.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_id_1": {
                    "type": "string",
                    "description": "4-character PDB identifier for the first structure (e.g., '1ABC'). Use either this or pdb_path_1.",
                },
                "pdb_path_1": {
                    "type": "string",
                    "description": "Path to local PDB file for the first structure. Use either this or pdb_id_1.",
                },
                "chain_id_1": {"type": "string", "description": "Chain identifier in the first structure (e.g., 'A')"},
                "pdb_id_2": {
                    "type": "string",
                    "description": "4-character PDB identifier for the second structure (e.g., '6VXX'). Use either this or pdb_path_2.",
                },
                "pdb_path_2": {
                    "type": "string",
                    "description": "Path to local PDB file for the second structure. Use either this or pdb_id_2.",
                },
                "chain_id_2": {"type": "string", "description": "Chain identifier in the second structure (e.g., 'A')"},
            },
            "required": [],
        },
        "check_fn": None,
    },
    {
        "name": "get_functional_annotations",
        "toolset": "structure",
        "description": "Retrieve functional annotations for a PDB structure chain including UniProt ID, GO terms, and CATH/SCOP domain classifications.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_id": {"type": "string", "description": "4-character PDB identifier (e.g., '1UBQ', '6VXX')"},
                "chain_id": {"type": "string", "description": "Chain identifier (e.g., 'A', 'B')"},
            },
            "required": [],
        },
        "check_fn": None,
    },
    {
        "name": "analyze_bfactors",
        "toolset": "structure",
        "description": "Analyze per-residue B-factors (temperature factors) in a protein structure to identify rigid, ordered, and flexible regions.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_id": {
                    "type": "string",
                    "description": "4-character PDB identifier (e.g., '1ABC', '6VXX'). Use either this or pdb_path.",
                },
                "pdb_path": {"type": "string", "description": "Path to local PDB file. Use either this or pdb_id."},
                "chain_id": {"type": "string", "description": "Chain identifier (e.g., 'A', 'B')"},
                "residue_range": {
                    "type": "string",
                    "description": "Optional residue range to analyze in format 'start-end' (e.g., '1-50'). If not provided, analyzes the entire chain.",
                    "default": None,
                },
            },
            "required": [],
        },
        "check_fn": None,
    },
    {
        "name": "compute_charge_distribution",
        "toolset": "analysis",
        "description": "Compute the charge distribution of a protein structure at a given pH, identifying charged residues and charge clusters (3+ residues within 8 Angstroms).",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_id": {
                    "type": "string",
                    "description": "4-character PDB identifier (e.g., '1ABC', '6VXX'). Use either this or pdb_path.",
                },
                "pdb_path": {
                    "type": "string",
                    "description": "Path to local PDB/mmCIF file. Use either this or pdb_id.",
                },
                "chain_id": {"type": "string", "description": "Chain identifier (e.g., 'A', 'B')"},
                "ph": {
                    "type": "number",
                    "description": "pH value for charge calculation (default: 7.4)",
                    "default": 7.4,
                },
                "residue_range": {
                    "type": "string",
                    "description": "Optional residue range to analyze, format 'start-end' (e.g., '1-50')",
                    "default": None,
                },
            },
            "required": ["chain_id"],
        },
        "check_fn": None,
    },
    {
        "name": "get_conservation_scores",
        "toolset": "analysis",
        "description": "Retrieve evolutionary conservation scores for a protein structure from ConSurf-DB, classifying residues as buried (1-3), intermediate (4-6), or exposed (7-9). Falls back to RCSB GraphQL if ConSurf is unavailable.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_id": {"type": "string", "description": "4-character PDB identifier (e.g., '1ABC', '6VXX')"},
                "chain_id": {"type": "string", "description": "Chain identifier (e.g., 'A', 'B')"},
            },
            "required": [],
        },
        "check_fn": "_check_consurfdb",
    },
    {
        "name": "check_ramachandran",
        "toolset": "structure",
        "description": "Analyze Ramachandran plot statistics for a protein chain, classifying each residue as favored, allowed, or outlier based on its phi/psi angles. Handles GLY and PRO specially.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_id": {
                    "type": "string",
                    "description": "4-character PDB identifier (e.g., '1ABC', '6VXX'). Use either this or pdb_path.",
                },
                "pdb_path": {"type": "string", "description": "Path to local PDB file. Use either this or pdb_id."},
                "chain_id": {"type": "string", "description": "Chain identifier (e.g., 'A', 'B')"},
                "residue_range": {
                    "type": "string",
                    "description": "Optional residue range to analyze (e.g., '1-100' or '50'). If not specified, analyzes the entire chain.",
                    "default": None,
                },
            },
            "required": [],
        },
        "check_fn": None,
    },
    {
        "name": "search_structural_homologs",
        "toolset": "analysis",
        "description": "Search for structural homologs of a protein chain using Foldseek. Submit a PDB chain, search against databases (pdb100, afdb50), poll until complete, and return parsed homolog results with alignment statistics.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_id": {"type": "string", "description": "4-character PDB identifier (e.g., '1ABC', '6VXX')"},
                "chain_id": {"type": "string", "description": "Chain identifier (e.g., 'A', 'B')"},
                "databases": {
                    "type": "array",
                    "description": "List of Foldseek databases to search against",
                    "default": ["pdb100", "afdb50"],
                    "items": {"type": "string"},
                },
                "max_hits": {"type": "integer", "description": "Maximum number of hits to return", "default": 10},
            },
            "required": [],
        },
        "check_fn": "_check_foldseek",
    },
    {
        "name": "fast_relax",
        "toolset": "structure",
        "description": "Perform FastRelax energy minimization on a protein structure using PyRosetta. Relaxes the structure by optimizing sidechain and backbone positions to reduce steric clashes and improve stereochemistry. Supports both PDB and mmCIF input formats.",
        "parameters": {
            "type": "object",
            "properties": {
                "input_path": {"type": "string", "description": "Path to input structure file (.pdb or .cif)"},
                "sidechain_only": {
                    "type": "boolean",
                    "description": "If True, only relax sidechain chi angles; if False, also relax backbone phi/psi angles",
                    "default": True,
                },
                "iterations": {
                    "type": "integer",
                    "description": "Maximum number of minimization iterations",
                    "default": 250,
                },
            },
            "required": [],
        },
        "check_fn": "_check_pyrosetta",
    },
    {
        "name": "analyze_interface_energies",
        "toolset": "structure",
        "description": "Analyze per-residue interface energies between a binder chain and all other chains in a protein complex using PyRosetta. Identifies interface residues within a distance cutoff and computes Rosetta dG for each. Optionally generates a bar plot showing favorable (blue, negative REU) and unfavorable (red, positive REU) residues.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_path": {"type": "string", "description": "Path to PDB or mmCIF file on disk"},
                "binder_chain": {"type": "string", "description": "Binder chain ID (e.g., 'A', 'B')"},
                "cutoff": {
                    "type": "number",
                    "default": 4.0,
                    "description": "Heavy-atom distance cutoff in Angstroms for interface detection (default: 4.0)",
                },
                "plot_output": {
                    "type": "string",
                    "description": "Optional path for matplotlib plot output (e.g., 'interface_energies.png')",
                },
            },
            "required": ["pdb_path", "binder_chain"],
        },
        "check_fn": "_check_pyrosetta",
    },
    {
        "name": "score_interface",
        "toolset": "structure",
        "description": "Compute comprehensive interface scoring metrics for protein-protein complexes using PyRosetta's InterfaceAnalyzerMover. Calculates interface dG, shape complementarity (sc), packstat, buried unsatisfied hbonds, and delta SASA. Optionally applies FastRelax before scoring. Also identifies hotspot residues at the interface using Bio.PDB and scipy cKDTree.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_path": {
                    "type": "string",
                    "description": "Path to the PDB or mmCIF file containing the protein complex",
                },
                "binder_chains": {
                    "type": "string",
                    "default": "B",
                    "description": "Chain identifier(s) for the binder (e.g., 'B' or 'B,C' for multiple)",
                },
                "target_chain": {
                    "type": "string",
                    "default": "A",
                    "description": "Chain identifier for the target (e.g., 'A')",
                },
                "relax_structure": {
                    "type": "boolean",
                    "default": True,
                    "description": "Whether to apply FastRelax before scoring (recommended for most cases)",
                },
            },
            "required": ["pdb_path"],
        },
        "check_fn": "_check_pyrosetta",
    },
    {
        "name": "renumber_pdb",
        "toolset": "structure",
        "description": "Renumber residues in a PDB file with control over gap handling and chain ID assignment. Saves output as {stem}_renum.pdb.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_path": {"type": "string", "description": "Path to the input PDB file"},
                "merge_chains": {
                    "type": "boolean",
                    "description": "If True, merge all chains into one with a 50-residue gap between chains",
                    "default": False,
                },
                "no_skip": {
                    "type": "boolean",
                    "description": "If True, number residues 1-N continuously ignoring all gaps in the original numbering",
                    "default": False,
                },
                "target_chain": {
                    "type": "string",
                    "description": "Force a specific final chain ID for the whole file (default: 'A')",
                    "default": "A",
                },
            },
            "required": [],
        },
        "check_fn": None,
    },
    {
        "name": "compute_normal_modes",
        "toolset": "dynamics",
        "description": "Compute normal modes (ANM/GNM) for a protein chain and analyze dynamics including fluctuations and hinge residues.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_id": {
                    "type": "string",
                    "description": "4-character PDB identifier (e.g., '1ABC', '6VXX'). Use either this or pdb_path.",
                },
                "pdb_path": {
                    "type": "string",
                    "description": "Path to local PDB/mmCIF file. Use either this or pdb_id.",
                },
                "chain_id": {"type": "string", "description": "Chain identifier (e.g., 'A', 'B')"},
                "n_modes": {"type": "integer", "description": "Number of modes to compute", "default": 20},
                "cutoff": {
                    "type": "number",
                    "description": "Cutoff distance for ANM Hessian and GNM Kirchhoff (in Angstroms)",
                    "default": 15.0,
                },
            },
            "required": [],
        },
        "check_fn": "_check_prody",
    },
    {
        "name": "compute_cross_correlations",
        "toolset": "dynamics",
        "description": "Compute cross-correlation matrix from ANM modes to identify correlated and anti-correlated residue pairs.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_id": {
                    "type": "string",
                    "description": "4-character PDB identifier (e.g., '1ABC', '6VXX'). Use either this or pdb_path.",
                },
                "pdb_path": {
                    "type": "string",
                    "description": "Path to local PDB/mmCIF file. Use either this or pdb_id.",
                },
                "chain_id": {"type": "string", "description": "Chain identifier (e.g., 'A', 'B')"},
                "source_residue": {
                    "type": "integer",
                    "description": "Optional source residue number to extract correlations for a specific residue",
                    "required": False,
                },
                "n_modes": {
                    "type": "integer",
                    "description": "Number of modes to use for cross-correlation calculation",
                    "default": 20,
                },
            },
            "required": [],
        },
        "check_fn": "_check_prody",
    },
    {
        "name": "predict_hinge_regions",
        "toolset": "dynamics",
        "description": "Predict hinge regions in a protein chain using Gaussian Network Model (GNM) analysis. Identifies zero-crossings in slow mode eigenvectors as potential hinge points that separate protein domains or subdomains.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_id": {
                    "type": "string",
                    "description": "4-character PDB identifier (e.g., '1ABC', '6VXX'). Use either this or pdb_path.",
                },
                "pdb_path": {
                    "type": "string",
                    "description": "Path to local PDB/mmCIF file. Use either this or pdb_id.",
                },
                "chain_id": {"type": "string", "description": "Chain identifier (e.g., 'A', 'B')"},
                "n_modes": {
                    "type": "integer",
                    "description": "Number of slow modes to analyze for hinge detection",
                    "default": 3,
                },
            },
            "required": ["chain_id"],
        },
        "check_fn": "_check_prody",
    },
    {
        "name": "compute_perturbation_response",
        "toolset": "dynamics",
        "description": "Perform perturbation response scanning (PRS) to predict how perturbing one residue (e.g., ligand binding) propagates through the structure. Uses ENM-based approximation of allosteric signal propagation. Returns which residues respond most strongly.",
        "parameters": {
            "type": "object",
            "properties": {
                "pdb_id": {
                    "type": "string",
                    "description": "4-character PDB identifier (e.g., '1ABC', '6VXX'). Use either this or pdb_path.",
                },
                "pdb_path": {
                    "type": "string",
                    "description": "Path to local PDB/mmCIF file. Use either this or pdb_id.",
                },
                "chain_id": {"type": "string", "description": "Chain identifier (e.g., 'A', 'B')"},
                "source_residue": {
                    "type": "integer",
                    "description": "Residue number to perturb (e.g., ligand binding site)",
                },
                "n_modes": {
                    "type": "integer",
                    "description": "Number of modes to use for PRS calculation",
                    "default": 20,
                },
            },
            "required": ["chain_id", "source_residue"],
        },
        "check_fn": "_check_prody",
    },
]


def get_tool_schemas_for_planning(toolsets=None):
    """Get tool schemas filtered by toolsets.

    Args:
        toolsets: Optional list of toolset names to filter by.
                 If None, returns all tools.

    Returns:
        List of tool schema dicts matching the specified toolsets.
    """
    if toolsets is None:
        return TOOL_SCHEMAS
    return [t for t in TOOL_SCHEMAS if t.get("toolset") in toolsets]


def build_compact_tool_list(toolsets=None):
    """Build a compact tool list for planning prompts."""
    schemas = get_tool_schemas_for_planning(toolsets)
    lines = []
    for schema in schemas:
        name = schema.get("name", "unknown")
        desc = (schema.get("description") or "No description").split("\n")[0][:80]
        params = schema.get("parameters") or {}
        props = params.get("properties", {})
        param_names = list(props.keys())
        if param_names:
            lines.append(f"- {name}: {desc} (params: {', '.join(param_names)})")
        else:
            lines.append(f"- {name}: {desc}")
    return "\n".join(lines) if lines else "No tools available"
